# Pipeline configuration file for ROS video_publisher.py

# video files
video_path_left_in:  /home/wardlewo/Reggie/data/ros/20240531_circle_base/stero_config/left/GX011005.MP4
video_path_right_in: /home/wardlewo/Reggie/data/ros/20240531_circle_base/stero_config/right/GX010370.MP4

#Not implemented yet
# output directory
save_dir: /home/wardlewo/Reggie/data/urchin_data_output

